#add your plugin path here to compile isolate library with main execute

#add_subdirectory(${CMAKE_SOURCE_DIR}/plugin/TemperatureControlPanel)

#add_subdirectory(${CMAKE_SOURCE_DIR}/plugin/KnobControlPanel/level3)

#add_subdirectory(${CMAKE_SOURCE_DIR}/plugin/KnobControlPanel/level5)

add_subdirectory(${CMAKE_SOURCE_DIR}/plugin/compile)
