/*
* FileName: device.h
* Author:    wjian
* Date:      2023-11-23
* Version:   v1.0
* Description: device abstract definition.
* */
#ifndef __DEVICE_H__
#define __DEVICE_H__

typedef enum {
    DEVICE_ATTRI_UNKNOWN,
    DEVICE_ATTRI_SENSOR,     /* 传感器 */
    DEVICE_ATTRI_DISPLAY,    /* 显示器 */
    DEVICE_ATTRI_CONTROLLER, /* 控制器 */
    DEVICE_ATTRI_ACTUATOR,   /* 执行器 */
} DeviceAttri_u;

typedef enum {
    Z3_PANEL_ONE_KEY,
    Z3_PANEL_TWO_KEY,
    Z3_PANEL_THREE_KEY,
    Z3_PANEL_FOUR_KEY,
    Z3_PANEL_FIVE_KEY,
    Z3_PANEL_SIX_KEY,
    Z3_PANEL_SEVEN_KEY,
    Z3_PANEL_EIGHT_KEY,

    KNX_PANEL_ONE_KEY,
    KNX_PANEL_TWO_KEY,
    KNX_PANEL_THREE_KEY,
    KNX_PANEL_FOUR_KEY,
    KNX_PANEL_FIVE_KEY,
    KNX_PANEL_SIX_KEY,
    KNX_PANEL_SEVEN_KEY,
    KNX_PANEL_EIGHT_KEY,

    MODBUS_PANEL_ONE_KEY,
    MODBUS_PANEL_TWO_KEY,
    MODBUS_PANEL_THREE_KEY,
    MODBUS_PANEL_FOUR_KEY,
    MODBUS_PANEL_FIVE_KEY,
    MODBUS_PANEL_SIX_KEY,
    MODBUS_PANEL_SEVEN_KEY,
    MODBUS_PANEL_EIGHT_KEY,

    Z3_DEVICE_AIRCONDITION,
    Z3_DEVICE_VENTILATION,
    Z3_DEVICE_FLOORHEATING,

    KNX_DEVICE_AIRCONDITION,
    KNX_DEVICE_VENTILATION,
    KNX_DEVICE_FLOORHEATING,
    KNX_DEVICE_CURTAIN,

    MODBUS_DEVICE_AIRCONDITION,
    MODBUS_DEVICE_VENTILATION,
    MODBUS_DEVICE_FLOORHEATING,
    MODBUS_DEVICE_CURTAIN,
    MODBUS_DEVICE_AQI,
    MODBUS_DEVICE_PANNEL,
    MODBUS_DEVICE_HUMIDIFIER,
    MODBUS_DEVICE_PURIFIER,

    KNX_DIMMER_ONE_KEY,
    KNX_DIMMER_TWO_KEY,
    KNX_DIMMER_THREE_KEY,
    KNX_DIMMER_FOUR_KEY,

    KNX_MISC_PANEL_ONE_KEY,
    KNX_MISC_PANEL_TWO_KEY,
    KNX_MISC_PANEL_THREE_KEY,
    KNX_MISC_PANEL_FOUR_KEY,

} DeviceType_u;

typedef struct {

} Device_t;









const char *GetDeviceType (DeviceType_u type);

#endif