/*
 * Generated by CMake. DO NOT EDIT.
 * Source: version.h.in
 */

#ifndef __FIRMWARE_VERSION_H__
#define __FIRMWARE_VERSION_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Numeric Version for conditional compilation */
#define FW_VER_MAJOR          1
#define FW_VER_MINOR          0
#define FW_VER_PATCH          18

/* String Constants */
#define FW_VERSION_STR        "1.0.18"
#define FW_METADATA_STR       "57.e3df222.dirty"
#define FW_GIT_HASH           "e3df222"
#define FW_GIT_BRANCH         "master"
#define FW_GIT_AUTHOR         "wjian09"
#define FW_GIT_DATE           "2026-05-28 15:54:39"
#define FW_BUILD_TYPE         "Debug"

/* Dirty Flag (1 = Uncommitted changes present) */
#define FW_IS_DIRTY           1

/* Version Type String (Snapshot, RC, Release) */
#define FW_TYPE_STR           "Snapshot"

typedef struct {
    uint8_t major;
    uint8_t minor;
    uint8_t patch;
    uint8_t is_dirty;
    const char* version_str;
    const char* git_hash;
    const char* build_type;
} firmware_info_t;

static const firmware_info_t fw_info = {
    .major       = FW_VER_MAJOR,
    .minor       = FW_VER_MINOR,
    .patch       = FW_VER_PATCH,
    .is_dirty    = FW_IS_DIRTY,
    .version_str = FW_VERSION_STR,
    .git_hash    = FW_GIT_HASH,
    .build_type  = FW_BUILD_TYPE
};

#ifdef __cplusplus
}
#endif

#endif // __FIRMWARE_VERSION_H__
